apiVersion: apps/v1
kind: Deployment
metadata:
  name: instabug-goviolin-deployment
spec:
  selector:
    matchLabels:
      app: instabug-goviolin
  replicas: 1
  template:
    metadata: 
      labels:
        app: instabug-goviolin
    spec:
      containers:
      - name: instabug-goviolin
        image: george1998x/instabug-goviolin
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: instabug-goviolin-service
spec:
  selector:
    app: instabug-goviolin
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      nodePort: 32000
  type: LoadBalancer